AudioCDShopMVC/Models/Album.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace AudioCDShopMVC.Models
{
    public class Album
    {
        public int AlbumId { get; set; }
        public int GenreId { get; set; }
        public string AlbumTitle { get; set; }
        public string ArtistName { get; set; }
        public DateTime DateAdded { get; set; }
        public string CoverFileName { get; set; }
        public string Description { get; set; }
        public decimal Price { get; set; }
        public bool IsBestseller { get; set; }
        public bool IsHidden { get; set; }

        public virtual Genre Genre { get; set; }
    }
}

AudioCDShopMVC/Models/CartItem.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace AudioCDShopMVC.Models
{
    public class CartItem
    {
        public Album Album { get; set; }
        public int Quantity { get; set; }
        public decimal TotalPrice { get; set; }
    }
}

AudioCDShopMVC/Models/Genre.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace AudioCDShopMVC.Models
{
    public class Genre
    {
        public int GenreId { get; set; }
        public string Name { get; set; }
        public string Description {get; set;}
        public string IconFilename { get; set; }

        // właściwośc nawigacyjna
        public virtual ICollection<Album> Albums { get; set; }
    }
}

AudioCDShopMVC/Models/Order.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace AudioCDShopMVC.Models
{
    public class Order
    {
        public int OrderId { get; set; }

        public string UserId { get; set; }
        //public virtual ApplicationUser User { get; set; }

        //[Required(ErrorMessage = "Musisz wprowadzić imię")]
        [StringLength(100)]
        public string FirstName { get; set; }

       // [Required(ErrorMessage = "Musisz wprowadzć nazwisko")]
        [StringLength(150)]
        public string LastName { get; set; }

        //[Required(ErrorMessage = "Nie wprowadzono adresu")]
       // [StringLength(150)]
        public string Address { get; set; }

        [Required(ErrorMessage = "Wprowadź kod pocztowy i miasto")]
        [StringLength(50)]
        public string CodeAndCity { get; set; }

       // [Required(ErrorMessage = "Musisz wprowadzić numer telefonu")]
       // [StringLength(20)]
       // [RegularExpression(@"(\+\d{2})*[\d\s-]+",
       //     ErrorMessage = "Błędny format numeru telefonu.")]
        public string PhoneNumber { get; set; }

        //[Required(ErrorMessage = "Wprowadź swój adres e-mail.")]
       // [EmailAddress(ErrorMessage = "Błędny format adresu e-mail.")]
        public string Email { get; set; }

        public string Comment { get; set; }
        public DateTime DateCreated { get; set; }
        public OrderState OrderState { get; set; }

        public decimal TotalPrice { get; set; }

        public List<OrderItem> OrderItems { get; set; }
    }
    public enum OrderState
    {
        New,
        Shipped,
    }
}

AudioCDShopMVC/Models/OrderItem.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace AudioCDShopMVC.Models
{
    public class OrderItem
    {
        public int OrderItemId { get; set; }
        public int OrderId { get; set; }
        public int AlbumId { get; set; }
        public int Quantity { get; set; }
        public decimal UnitPrice { get; set; }

        // właściwości nawigacyjne
        public virtual Album Album { get; set; }
        public virtual Order Order { get; set; }
    }
}

AudioCDShopMVC/ViewModels/HomeViewModel.cs
using AudioCDShopMVC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace AudioCDShopMVC.ViewModels
{
    public class HomeViewModel
    {
        public IEnumerable<Album> Bestsellers { get; set; }
        public IEnumerable<Album> NewArrivals { get; set; }
        public IEnumerable<Genre> Genres { get; set; }

    }
}

AudioCDShopMVC/Controllers/HomeController.cs
using AudioCDShopMVC.DAL;
using AudioCDShopMVC.Infrastructure;
using AudioCDShopMVC.Models;
using AudioCDShopMVC.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AudioCDShopMVC.Controllers
{
    public class HomeController : Controller
    {
        private StoreContext db = new StoreContext();
        // GET: Home
        public ActionResult Index()
        {
            var genres = db.Genres.ToList();

            ICacheProvider cache = new DefaultCacheProvider();

            List<Album> newArrivals = new List<Album>();

            if (cache.IsSet(Consts.NewItemsCacheKey))
            {
                newArrivals = cache.Get(Consts.NewItemsCacheKey) as List<Album>;
            }
            else
            {
                newArrivals = db.Albums.Where(a => !a.IsHidden).OrderByDescending(a => a.DateAdded).Take(3).ToList();
                cache.Set(Consts.NewItemsCacheKey, newArrivals, 30);
            }

            
            var bessellers = db.Albums.Where(a => !a.IsHidden && a.IsBestseller).OrderBy(g => Guid.NewGuid()).Take(3).ToList();

            var vm = new HomeViewModel()
            { Bestsellers = bessellers, Genres = genres, NewArrivals = newArrivals };

            return View(vm);
        }
       
        public ActionResult StaticContent(string viewname)
        {
            return View(viewname);

        }
    }
}

AudioCDShopMVC/Controllers/StoreController.cs
using AudioCDShopMVC.DAL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AudioCDShopMVC.Controllers
{
    public class StoreController : Controller
    {
        StoreContext db = new StoreContext();
        // GET: Store
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Details(int id)
        {
            var album = db.Albums.Find(id);
            return View(album);
        }
        public ActionResult List(string genrename, string searchQuery = null)
        {
            //pobieranie wszystkich albumów z wybranego gatunku
            var genre = db.Genres.Include("Albums").Where(g => g.Name.ToUpper() == genrename.ToUpper()).Single();
            var albums = genre.Albums.Where(a => (searchQuery == null ||
            a.AlbumTitle.ToLower().Contains(searchQuery.ToLower()) ||
            a.ArtistName.ToLower().Contains(searchQuery.ToLower())) &&
            !a.IsHidden);

            if (Request.IsAjaxRequest())
            {
                return PartialView("_ProductList", albums);
            }

            return View(albums);
        }
        [ChildActionOnly]
        [OutputCache(Duration = 80000)]
        public ActionResult GenresMenu()
        {
            var genres = db.Genres.ToList();
            return PartialView("_GenresMenu", genres);
        }

        public ActionResult AlbumsSuggestions(string term)
        {
            var albums = this.db.Albums.Where(a => !a.IsHidden && a.AlbumTitle.ToLower().Contains(term.ToLower()))
                .Take(5).Select(a => new { label = a.AlbumTitle });

            return Json(albums, JsonRequestBehavior.AllowGet);
        }
    }
}

AudioCDShopMVC/Controllers/ViewSwitcherController.cs
using System.Web.Mvc;
using System.Web.WebPages;

namespace AudioCDShopMVC.Controllers
{
    public class ViewSwitcherController : Controller
    {
        public RedirectResult SwitchView(bool mobile, string returnUrl) {
            if (Request.Browser.IsMobileDevice == mobile)
                HttpContext.ClearOverriddenBrowser();
            else
                HttpContext.SetOverriddenBrowser(mobile ? BrowserOverride.Mobile : BrowserOverride.Desktop);

            return Redirect(returnUrl);
        }
    }
}

AudioCDShopMVC/Views/Home/Index.cshtml
@model AudioCDShopMVC.ViewModels.HomeViewModel
@using AudioCDShopMVC.Infrastructure
@{
    ViewBag.Title = "AudioCDShop";
}
<nav class="genres-horizontal">
    <ul>
        @foreach (var genre in Model.Genres)
            {
            <li>
                <a href="@Url.Action("List", "Store", new { genrename = genre.Name.ToLower() })"
                   style="background-image: url(@Url.GenreIconPath(genre.IconFilename)); ">
                    @genre.Name

                </a>
            </li>
        }
    </ul>
    <a href="">
        <img id="baner-main" src="../Content/Images/baner-main-new.png" />
    </a>
</nav>
<section>
    <ul class="ThreeColumnsCoversList large-cover-list">
        @foreach (var newArrival in Model.NewArrivals)
        {
            <li>
                <article>
                    <a class="addtocartlink" href="@Url.Action("AddToCart", "Cart", new { id = newArrival.AlbumId })">
                        <img src="../Content/Images/cart.png" />
                    </a>
                    <a class="productdetailslink" href="@Url.Action("Details", "Store", new { id = newArrival.AlbumId })">
                        <div class="newFlag"></div>
                        <img class="album-cover" src="@Url.AlbumCoverPath(newArrival.CoverFileName)" />
                        <h1>
                            @newArrival.ArtistName - @newArrival.AlbumTitle
                        </h1>
                    </a>
                </article>
            </li>
        }
    </ul>
</section>

<section>
    <ul class="ThreeColumnsCoversList large-cover-list">
        @foreach (var bestseller in Model.Bestsellers)
        {
            <li>
                <article>
                    <a class="addtocartlink" href="@Url.Action("AddToCart", "Cart", new { id = bestseller.AlbumId })" >
                        <img src="../Content/Images/cart.png" />
                    </a>
                    <a class="productdetailslink" href="@Url.Action("Details", "Store", new { id = bestseller.AlbumId })" >
                        <div class="bestsellerFlag"></div>
                        <img class="album-cover" src="@Url.AlbumCoverPath(bestseller.CoverFileName)" />
                        <h1>
                            @bestseller.ArtistName - @bestseller.AlbumTitle
                        </h1>
                    </a>
                </article>
            </li>
        }
    </ul>
</section>

AudioCDShopMVC/Views/Home/Index.mobile.cshtml
@model AudioCDShopMVC.ViewModels.HomeViewModel
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Indexmobile</title>

    <link rel="stylesheet" href="http://code.jquery.com/mobile/1.4.5/jquery.mobile-1.4.5.min.css" />
    <script src="http://code.jquery.com/jquery-1.11.1.min.js"></script>
    <script src="http://code.jquery.com/mobile/1.4.5/jquery.mobile-1.4.5.min.js"></script>

</head>
<body>
    @Html.Partial("_ViewSwitcher")
    <h3 class="ui-bar ui-bar-a">Witamy w sklepie AudioCDShop!</h3>
    <div class="ui-body">

        <ul data-role="listview" data-inset="true" data-divider-theme="a">

            <li data-role="list-divider">Nowości</li>

            @foreach (var newArrival in Model.NewArrivals)
            {
                <li>
                    <a href="@Url.Action("Details", "Store", new { id = newArrival.AlbumId })" data-ajax="false">
                        <img src="@Url.Content("~/Content/Covers/" + newArrival.CoverFileName)">
                        <h2>@newArrival.AlbumTitle</h2>
                        <p>@newArrival.ArtistName</p>
                    </a>
                </li>
            }

            <li data-role="list-divider">Bestsellery</li>

            @foreach (var bestseller in Model.Bestsellers)
            {
                <li>
                    <a href="@Url.Action("Details", "Store", new { id = bestseller.AlbumId })" data-ajax="false">
                        <img src="@Url.Content("~/Content/Covers/" + bestseller.CoverFileName)">
                        <h2>@bestseller.AlbumTitle</h2>
                        <p>@bestseller.ArtistName</p>
                    </a>
                </li>
            }

        </ul>

        <br />

        <ul data-role="listview" data-inset="true" data-filter-placeholder="Szukaj gatunku muzycznego..." data-filter="true">

            @foreach (var genre in Model.Genres)
            {
                <li>
                    <a href="@Url.Action("List", "Store", new { genrename = genre.Name.ToLower() })" data-ajax="false">@genre.Name</a>
                </li>
            }

        </ul>
        <br />

        <div data-role="footer">
            <div data-role="navbar">
                <ul>
                    <li><a href="https://www.facebook.com/eduwebpl" data-ajax="false" data-icon="heart">Facebook</a></li>
                    <li><a href="@Url.Action("StaticContent", "Home", new { viewname = "Onas" })" data-ajax="false" data-icon="info">O nas</a></li>
                    <li><a href="@Url.Action("StaticContent", "Home", new { viewname = "Kontakt" })" data-ajax="false" data-icon="mail">Kontakt</a></li>
                </ul>
            </div><!-- /navbar -->
        </div><!-- /footer -->

    </div>
</body>
</html>

AudioCDShopMVC/Views/Home/Kontakt.cshtml
@{
    ViewBag.Title = "Kontakt";
}

<div style="margin-top: 20px; line-height: 22px;">
    Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.
    Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.
    Fusce non varius purus aenean nec magna felis fusce vestibulum velit mollis odio sollicitudin lacinia aliquam posuere, sapien elementum lobortis tincidunt, turpis dui ornare nisl, sollicitudin interdum turpis nunc eget.
    Sem nulla eu ultricies orci praesent id augue nec lorem pretium congue sit amet ac nunc fusce iaculis lorem eu diam hendrerit at mattis purus dignissim vivamus mauris tellus, fringilla.
    Vel dapibus a, blandit quis erat vivamus elementum aliquam luctus etiam fringilla pretium sem vitae sodales mauris id nulla est praesent laoreet, metus vel auctor aliquam, eros purus vulputate leo.
    Eget consequat neque quam id tellus duis ultricies tempor tortor, vitae dignissim ligula mattis nec in hac habitasse platea dictumst ut arcu enim, dictum quis ultrices id, sagittis eget nulla.
    Sed nunc mi, congue ut ultricies ac, varius a eros donec porttitor, libero fermentum fringilla laoreet, eros arcu sodales ante, ut dictum risus lectus vel quam integer ultricies, nunc eget.
    Elementum euismod, orci enim vestibulum orci, nec suscipit urna odio et tellus suspendisse suscipit orci sit amet sem venenatis nec lobortis sem suscipit nullam nec imperdiet velit mauris eu nisi.
    A felis imperdiet porta at ac nulla vivamus faucibus felis nec dolor pretium eget pellentesque dolor suscipit maecenas vitae enim arcu, at tincidunt nunc pellentesque eleifend vulputate lacus, vel semper.
    Sem ornare sit amet proin sem sapien, auctor vel faucibus id, aliquet vitae ipsum etiam auctor ultricies ante, at dapibus urna viverra sed nullam mi arcu, tempor vitae interdum a.integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.
    Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.
    Fusce non varius purus aenean nec magna felis fusce vestibulum velit mollis odio sollicitudin lacinia aliquam posuere, sapien elementum lobortis tincidunt, turpis dui ornare nisl, sollicitudin interdum turpis nunc eget.
    Sem nulla eu ultricies orci praesent id augue nec lorem pretium congue sit amet ac nunc fusce iaculis lorem eu diam hendrerit at mattis purus dignissim vivamus mauris tellus, fringilla.
    Vel dapibus a, blandit quis erat vivamus elementum aliquam luctus etiam fringilla pretium sem vitae sodales mauris id nulla est praesent laoreet, metus vel auctor aliquam, eros purus vulputate leo.
    Eget consequat neque quam id tellus duis ultricies tempor tortor, vitae dignissim ligula mattis nec in hac habitasse platea dictumst ut arcu enim, dictum quis ultrices id, sagittis eget nulla.
    Sed nunc mi, congue ut ultricies ac, varius a eros donec porttitor, libero fermentum fringilla laoreet, eros arcu sodales ante, ut dictum risus lectus vel quam integer ultricies, nunc eget.
    Elementum euismod, orci enim vestibulum orci, nec suscipit urna odio et tellus suspendisse suscipit orci sit amet sem venenatis nec lobortis sem suscipit nullam nec imperdiet velit mauris eu nisi.
    A felis imperdiet porta at ac nulla vivamus faucibus felis nec dolor pretium eget pellentesque dolor suscipit maecenas vitae enim arcu, at tincidunt nunc pellentesque eleifend vulputate lacus, vel semper.
    Sem ornare sit amet proin sem sapien, auctor vel faucibus id, aliquet vitae ipsum etiam auctor ultricies ante, at dapibus urna viverra sed nullam mi arcu, tempor vitae interdum a.

</div>

AudioCDShopMVC/Views/Home/Onas.cshtml
@{
    ViewBag.Title = "Onas";
    Layout = "~/Views/Shared/_StoreLayout.cshtml";
}

<h2>Onas</h2>

<div style="margin-top: 20px; line-height: 22px;">
    Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante fusce non varius purus aenean nec magna felis fusce vestibulum velit mollis odio sollicitudin lacinia aliquam posuere, sapien elementum lobortis tincidunt, turpis dui ornare nisl, sollicitudin interdum turpis nunc eget.
    Sem nulla eu ultricies orci praesent id augue nec lorem pretium congue sit amet ac nunc fusce iaculis lorem eu diam hendrerit at mattis purus dignissim vivamus mauris tellus, fringilla vel dapibus a, blandit quis erat vivamus elementum aliquam luctus etiam fringilla pretium sem vitae sodales mauris id nulla est praesent laoreet, metus vel auctor aliquam, eros purus vulputate leo.
    Eget consequat neque quam id tellus duis ultricies tempor tortor, vitae dignissim ligula mattis nec in hac habitasse platea dictumst ut arcu enim, dictum quis ultrices id, sagittis eget nulla sed nunc mi, congue ut ultricies ac, varius a eros donec porttitor, libero fermentum fringilla laoreet, eros arcu sodales ante, ut dictum risus lectus vel quam integer ultricies, nunc eget.
    Elementum euismod, orci enim vestibulum orci, nec suscipit urna odio et tellus suspendisse suscipit orci sit amet sem venenatis nec lobortis sem suscipit nullam nec imperdiet velit mauris eu nisi a felis imperdiet porta at ac nulla vivamus faucibus felis nec dolor pretium eget pellentesque dolor suscipit maecenas vitae enim arcu, at tincidunt nunc pellentesque eleifend vulputate lacus, vel semper.
    Sem ornare sit amet proin sem sapien, auctor vel faucibus id, aliquet vitae ipsum etiam auctor ultricies ante, at dapibus urna viverra sed nullam mi arcu, tempor vitae interdum a, sodales non urna vestibulum dignissim auctor mauris, ac elementum purus fermentum vitae duis placerat laoreet risus, sit amet eleifend tellus lobortis non vivamus iaculis dapibus leo a ornare cras vel.
    Sem at felis convallis mollis posuere ultrices dolor sed tellus arcu, accumsan a consectetur sit amet, volutpat eget lorem phasellus quis ipsum orci integer sodales tincidunt nibh a elementum ut ac libero nec orci euismod euismod nec at nulla duis malesuada faucibus porta aliquam nec consequat eros sed porttitor placerat dolor, accumsan imperdiet neque ornare in aenean non elit non.
    Leo porta mattis mauris non dolor nunc, id congue odio donec tellus nisl, semper id consectetur vitae, dapibus dictum nisl morbi sed augue purus sed dictum diam convallis tortor interdum volutpat phasellus dapibus arcu sit amet neque vulputate sed elementum orci fringilla in hac habitasse platea dictumst maecenas ut dui diam curabitur adipiscing vestibulum libero, nec varius dui pulvinar eget.
    Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; aliquam duineque, varius eu laoreet vel.
</div>

AudioCDShopMVC/Views/Home/Wysyłka.cshtml
@{
    ViewBag.Title = "Wysyłka";
    Layout = "~/Views/Shared/_StoreLayout.cshtml";
}

<h2>Wysyłka</h2>

<div style="margin-top: 20px; line-height: 22px;">
    Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante fusce non varius purus aenean nec magna felis fusce vestibulum velit mollis odio sollicitudin lacinia aliquam posuere, sapien elementum lobortis tincidunt, turpis dui ornare nisl, sollicitudin interdum turpis nunc eget.
    Sem nulla eu ultricies orci praesent id augue nec lorem pretium congue sit amet ac nunc fusce iaculis lorem eu diam hendrerit at mattis purus dignissim vivamus mauris tellus, fringilla vel dapibus a, blandit quis erat vivamus elementum aliquam luctus etiam fringilla pretium sem vitae sodales mauris id nulla est praesent laoreet, metus vel auctor aliquam, eros purus vulputate leo.
    Eget consequat neque quam id tellus duis ultricies tempor tortor, vitae dignissim ligula mattis nec in hac habitasse platea dictumst ut arcu enim, dictum quis ultrices id, sagittis eget nulla sed nunc mi, congue ut ultricies ac, varius a eros donec porttitor, libero fermentum fringilla laoreet, eros arcu sodales ante, ut dictum risus lectus vel quam integer ultricies, nunc eget.
    Elementum euismod, orci enim vestibulum orci, nec suscipit urna odio et tellus suspendisse suscipit orci sit amet sem venenatis nec lobortis sem suscipit nullam nec imperdiet velit mauris eu nisi a felis imperdiet porta at ac nulla vivamus faucibus felis nec dolor pretium eget pellentesque dolor suscipit maecenas vitae enim arcu, at tincidunt nunc pellentesque eleifend vulputate lacus, vel semper.
    Sem ornare sit amet proin sem sapien, auctor vel faucibus id, aliquet vitae ipsum etiam auctor ultricies ante, at dapibus urna viverra sed nullam mi arcu, tempor vitae interdum a, sodales non urna vestibulum dignissim auctor mauris, ac elementum purus fermentum vitae duis placerat laoreet risus, sit amet eleifend tellus lobortis non vivamus iaculis dapibus leo a ornare cras vel.
    Sem at felis convallis mollis posuere ultrices dolor sed tellus arcu, accumsan a consectetur sit amet, volutpat eget lorem phasellus quis ipsum orci integer sodales tincidunt nibh a elementum ut ac libero nec orci euismod euismod nec at nulla duis malesuada faucibus porta aliquam nec consequat eros sed porttitor placerat dolor, accumsan imperdiet neque ornare in aenean non elit non.
    Leo porta mattis mauris non dolor nunc, id congue odio donec tellus nisl, semper id consectetur vitae, dapibus dictum nisl morbi sed augue purus sed dictum diam convallis tortor interdum volutpat phasellus dapibus arcu sit amet neque vulputate sed elementum orci fringilla in hac habitasse platea dictumst maecenas ut dui diam curabitur adipiscing vestibulum libero, nec varius dui pulvinar eget.
    Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; aliquam duineque, varius eu laoreet vel.
</div>

AudioCDShopMVC/Views/Shared/DisplayTemplates/CanonicalHelperModel.cshtml
@model MvcSiteMapProvider.Web.Html.Models.CanonicalHelperModel
@using System.Web.Mvc.Html
@using MvcSiteMapProvider.Web.Html.Models

@if (Model.CurrentNode != null && !string.IsNullOrEmpty(Model.CurrentNode.CanonicalUrl)) {
    <link rel="canonical" href="@Model.CurrentNode.CanonicalUrl" />
}

AudioCDShopMVC/Views/Shared/DisplayTemplates/MenuHelperModel.cshtml
@model MvcSiteMapProvider.Web.Html.Models.MenuHelperModel
@using System.Web.Mvc.Html
@using MvcSiteMapProvider.Web.Html.Models

<ul id="menu">
    @foreach (var node in Model.Nodes) { 
        <li>@Html.DisplayFor(m => node) 
            @if (node.Children.Any()) {
                @Html.DisplayFor(m => node.Children)
            }
        </li>
    }
</ul>

AudioCDShopMVC/Views/Shared/DisplayTemplates/MetaRobotsHelperModel.cshtml
@model MvcSiteMapProvider.Web.Html.Models.MetaRobotsHelperModel
@using System.Web.Mvc.Html
@using MvcSiteMapProvider.Web.Html.Models

@if (Model.CurrentNode != null && !string.IsNullOrEmpty(Model.CurrentNode.MetaRobotsContent)) {
    <meta name="robots" content="@Model.CurrentNode.MetaRobotsContent" />
}

AudioCDShopMVC/Views/Shared/_ViewSwitcher.cshtml
@if (Request.Browser.IsMobileDevice && Request.HttpMethod == "GET")
{
    <div class="view-switcher ui-bar-a">
        @if (ViewContext.HttpContext.GetOverriddenBrowser().IsMobileDevice)
        {
            @: Wyświetlana strona mobilna
            @Html.ActionLink("Przełącz", "SwitchView", "ViewSwitcher", new { mobile = false, returnUrl = Request.Url.PathAndQuery }, new { rel = "external" })
        } 
        else 
        {
            @: Wyświetlana strona klasyczna
            @Html.ActionLink("Przełącz", "SwitchView", "ViewSwitcher", new { mobile = true, returnUrl = Request.Url.PathAndQuery }, new { rel = "external" })
        }
    </div>
}

AudioCDShopMVC/Views/Store/_GenresMenu.cshtml
@model IEnumerable<AudioCDShopMVC.Models.Genre>




    <nav class="genres-vertical">
        <ul>
            @foreach (var genre in Model)
            {
            <li>
                <a href="@Url.Action("List", "Store", new { genrename = genre.Name.ToString() } )" 
                   style="background-image: url(@Url.GenreIconPath(genre.IconFilename)); ">
                    @genre.Name
                </a>
            </li>
            }
        </ul>
    </nav>

AudioCDShopMVC/Views/Store/_ProductList.cshtml
@model IEnumerable<AudioCDShopMVC.Models.Album>
@using AudioCDShopMVC.Infrastructure

<div id="productlist-section">
    <ul class="ThreeColumnsCoversList small-cover-list">
        @foreach (var album in Model)
            {
            <li>
                <article>
                    <a class="addtocartlink" href="@Url.Action("AddToCart", "Cart", new { id = album.AlbumId }) ">
                        <img src="@Url.Content("~/Content/Images/cart.png")" alt="Dodaj do koszyka" />
                    </a>
                    @if (album.IsBestseller)
                    {
                        <div class="bestsellerFlag"></div>
                    }
                    <a class="productdetailslink" href="@Url.Action("Details", "Store", new { id = album.AlbumId })">
                        <img class="album-cover" src="@Url.AlbumCoverPath(album.CoverFileName)" />
                        <h1>
                            @album.ArtistName - @album.AlbumTitle
                        </h1>
                    </a>
                </article>

            </li>
        }
    </ul>
</div>